package utnfc.isi.back.camionesservice.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;

/*
-- Tabla camion
CREATE TABLE camion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_transportista BIGINT,
    id_tipo_camion BIGINT,
    patente VARCHAR(20) NOT NULL UNIQUE,
    capacidad_peso DECIMAL(10,2) NOT NULL,
    capacidad_volumen DECIMAL(10,2) NOT NULL,
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    costo_base_km DECIMAL(10,2),
    consumo_combustible_promedio DECIMAL(5,2),
    CONSTRAINT fk_camion_transportista
        FOREIGN KEY(id_transportista)
        REFERENCES transportista(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_camion_tipo_camion
        FOREIGN KEY(id_tipo_camion)
        REFERENCES tipo_camion(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
 */

@Entity
@Table(name = "camion")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class Camion {

    //atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "patente",  nullable = false, length = 20)
    private String patente;

    @Column(name = "capacidad_peso",  nullable = false)
    private BigDecimal capacidadPeso;

    @Column(name = "capacidad_volumen",  nullable = false)
    private BigDecimal capacidadVolumen;

    @Column(name = "disponible", nullable = false)
    private boolean disponible = true;

    @Column(name = "costo_base_km")
    private BigDecimal costoBaseKm;

    @Column(name = "consumo_combustible_promedio")
    private BigDecimal consumoCombustiblePromedio;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_transportista")
    private Transportista transportista;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tipo_camion")
    private TipoCamion tipoCamion;

}
