package utnfc.isi.back.camionesservice.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;

/*
-- Tabla tarifa
CREATE TABLE tarifa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_camion BIGINT NOT NULL,
    rango_peso VARCHAR(20),
    rango_volumen VARCHAR(20),
    costo_km DECIMAL(10,2),
    costo_combustible DECIMAL(10,2),
    costo_estadia_deposito DECIMAL(10,2),
    CONSTRAINT fk_tarifa_tipo_camion
        FOREIGN KEY(id_tipo_camion)
        REFERENCES tipo_camion(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);
 */

@Entity
@Table(name = "tarifa")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class Tarifa {

    // atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name ="id", nullable = false)
    private Long id;

    @Column(name = "rango_peso", length = 20)
    private String rangoPeso;

    @Column(name = "rango_volumen", length = 20)
    private String rangoVolumen;

    @Column(name = "costo_km")
    private BigDecimal costoKm;

    @Column(name = "costo_combustible")
    private BigDecimal costoCombustible;

    @Column(name = "costo_estadia_deposito")
    private BigDecimal costoEstadiaDeposito;

    @ManyToOne
    @JoinColumn(name = "id_tipo_camion", nullable = false)
    private TipoCamion tipoCamion;

}
