package utnfc.isi.back.camionesservice.entity;

import jakarta.persistence.*;
import lombok.*;

/*
CREATE TABLE tipo_camion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);
 */

@Entity
@Table(name = "tipo_camion")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class TipoCamion {

    // atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name ="id", nullable = false)
    private Long id;

    @Column(name = "nombre", nullable = false, unique = true)
    private String nombre;
}
