package utnfc.isi.back.clientesservice.entity;

import jakarta.persistence.*;
import lombok.*;

/*
-- Tabla barrio
CREATE TABLE barrio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    id_ciudad BIGINT NOT NULL,
    CONSTRAINT fk_barrio_ciudad
        FOREIGN KEY(id_ciudad)
        REFERENCES ciudad(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
 */

@Entity
@Table(name = "barrio")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class Barrio {

    //atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "nombre", nullable = false, length = 50)
    private String nombre;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_ciudad", nullable = false)
    private Ciudad ciudad;
}