package utnfc.isi.back.clientesservice.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.*;

/*
-- Tabla ciudad
CREATE TABLE ciudad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    id_provincia BIGINT NOT NULL,
    CONSTRAINT fk_ciudad_provincia
        FOREIGN KEY(id_provincia)
        REFERENCES provincia(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
 */

@Entity
@Table(name = "ciudad")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Setter @Getter
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Ciudad {

    //atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "nombre", nullable = false, length = 50)
    private String nombre;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_provincia", nullable = false)
    private Provincia provincia;

}
