package utnfc.isi.back.clientesservice.entity;

import jakarta.persistence.*;
import lombok.*;
import java.util.List;


/*
-- Tabla cliente
CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    telefono VARCHAR(20) NOT NULL
);
 */

@Entity
@Table(name = "cliente")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class Cliente {

    //atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "documento", nullable = false, length = 30, unique = true)
    private String documento;

    @Column(name = "nombre", nullable = false, length = 50)
    private String nombre;

    @Column(name = "apellido", nullable = false, length = 50)
    private String apellido;

    @Column(name = "email", nullable = false, length = 100, unique = true)
    private String email;

    @Column(name = "telefono", nullable = false, length = 20)
    private String telefono;

    // listar direcciones del cliente
    @OneToMany(mappedBy = "cliente", fetch = FetchType.LAZY)
    private List<Direccion> direcciones;

}
