package utnfc.isi.back.clientesservice.entity;

import jakarta.persistence.*;
import lombok.*;

/*
-- Tabla direccion
CREATE TABLE direccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nro_calle VARCHAR(20) NOT NULL,
    id_calle BIGINT NOT NULL,
    id_cliente BIGINT,
    piso VARCHAR(10),
    dpto VARCHAR(10),
    observaciones VARCHAR(100),
    codigo_postal VARCHAR(20),
    CONSTRAINT fk_direccion_calle
        FOREIGN KEY (id_calle)
        REFERENCES calle(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_direccion_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
*/

@Entity
@Table(name = "direccion")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class Direccion {

    //atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "nro_calle", length = 20, nullable = false)
    private String nroCalle;

    @Column(name = "piso", length = 10)
    private String piso;

    @Column(name = "dpto", length = 10)
    private String dpto;

    @Column(name = "observaciones", length = 100)
    private String observaciones;

    @Column(name = "codigo_postal", length = 20)
    private String codigoPostal;

    @ManyToOne(optional = false)
    @JoinColumn(name = "id_calle", nullable = false)
    private Calle calle;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_cliente", nullable = false)
    private Cliente cliente;

    @OneToOne(mappedBy = "direccion", cascade = CascadeType.ALL)
    private Geolocalizacion geolocalizacion;
}

