package utnfc.isi.back.clientesservice.entity;

import jakarta.persistence.*;
import lombok.*;

/*
-- Tabla provincia
CREATE TABLE provincia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    id_pais BIGINT NOT NULL,
    CONSTRAINT fk_provincia_pais
        FOREIGN KEY(id_pais)
        REFERENCES pais(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
 */

@Entity
@Table(name = "provincia")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class Provincia {

    //atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "nombre", nullable = false, length = 50)
    private String nombre;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pais", nullable = false)
    private Pais pais;

}
