package utnfc.isi.back.contenedoresservice.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;

/*
-- Tabla contenedor
CREATE TABLE contenedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estado_contenedor BIGINT NOT NULL,
    peso DECIMAL(10,2) NOT NULL,
    volumen DECIMAL(10,2) NOT NULL,
    id_cliente BIGINT NOT NULL,
    CONSTRAINT fk_contenedor_cliente
        FOREIGN KEY(id_cliente)
        REFERENCES cliente(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_contenedor_estado_contenedor
        FOREIGN KEY(id_estado_contenedor)
        REFERENCES estado_contenedor(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
 */

@Entity
@Table(name = "contenedor")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class Contenedor {

    // atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "peso", nullable = false)
    private BigDecimal peso;

    @Column(name = "volumen", nullable = false)
    private BigDecimal volumen;

    @Column(name = "id_cliente", nullable = false)
    private Long idCliente;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_estado_contenedor", nullable = false)
    private EstadoContenedor estadoContenedor;
}
