package utnfc.isi.back.contenedoresservice.entity;

import jakarta.persistence.*;
import lombok.*;
/*
-- Tabla estado_contenedor
CREATE TABLE estado_contenedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL UNIQUE
);
 */

@Entity
@Table(name = "estado_contenedor")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class EstadoContenedor {

    // atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "nombre", nullable = false, length = 20, unique = true)
    private String nombre;
}
