package utnfc.isi.back.contenedoresservice.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.util.List;

/*
-- Tabla ruta
CREATE TABLE ruta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_tramos INTEGER NOT NULL,
    cantidad_depositos INTEGER NOT NULL,

-- nuevos campos calculados
    distancia_total_km DECIMAL(10,2),
    tiempo_total_minutos BIGINT,
    costo_total DECIMAL(10,2),
    seleccionada BOOLEAN DEFAULT FALSE,

    id_solicitud BIGINT NOT NULL,
    CONSTRAINT fk_ruta_solicitud
        FOREIGN KEY(id_solicitud)
        REFERENCES solicitud(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

 */

@Entity
@Table(name = "ruta")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class Ruta {

    // atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "cantidad_tramos", nullable = false)
    private Integer cantidadTramos;

    @Column(name = "cantidad_depositos", nullable = false)
    private Integer cantidadDepositos;

    @Column(name = "distancia_total_km")
    private BigDecimal distanciaTotalKm;

    @Column(name = "tiempo_total_minutos")
    private Long tiempoTotalMinutos;

    @Column(name = "costo_total")
    private BigDecimal costoTotal;

    @Column(name = "seleccionada")
    private boolean seleccionada = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_solicitud", nullable = false)
    private Solicitud solicitud;

    @OneToMany(mappedBy = "ruta", fetch = FetchType.LAZY)
    private List<Tramo> tramos;

}
