package utnfc.isi.back.contenedoresservice.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/*
-- Tabla solicitud
CREATE TABLE solicitud (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contenedor BIGINT NOT NULL,
    id_cliente BIGINT NOT NULL,
    id_estado_solicitud BIGINT NOT NULL,
    id_camion BIGINT,  -- nueva columna
    fecha_creacion DATE,
    costo_estimado DECIMAL(10,2),
    tiempo_estimado DECIMAL(10,2),
    costo_final DECIMAL(10,2),
    tiempo_real DECIMAL(10,2),

    CONSTRAINT fk_solicitud_contenedor
        FOREIGN KEY(id_contenedor)
        REFERENCES contenedor(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_solicitud_cliente
        FOREIGN KEY(id_cliente)
        REFERENCES cliente(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_solicitud_estado_solicitud
        FOREIGN KEY(id_estado_solicitud)
        REFERENCES estado_solicitud(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_solicitud_camion
        FOREIGN KEY(id_camion)
        REFERENCES camion(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

 */

@Entity
@Table(name = "solicitud")
@Data
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class Solicitud {

    // atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "id_cliente", nullable = false)
    private Long idCliente;

    @Column(name = "id_camion")
    private Long idCamion;

    @Column(name = "fecha_creacion", updatable = false)
    private LocalDateTime fechaCreacion;

    @Column(name = "costo_estimado")
    private BigDecimal costoEstimado;

    @Column(name = "costo_final")
    private BigDecimal costoFinal;

    @Column(name = "tiempo_real")
    private BigDecimal tiempoReal;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_contenedor", nullable = false)
    private Contenedor contenedor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_estado_solicitud", nullable = false)
    private EstadoSolicitud estadoSolicitud;
}
