package utnfc.isi.back.contenedoresservice.entity;

import jakarta.persistence.*;
import lombok.*;
import utnfc.isi.back.contenedoresservice.dto.TipoTramoDTO;

/*
-- Tabla tipo_tramo
CREATE TABLE tipo_tramo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);
 */

@Entity
@Table(name = "tipo_tramo")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@Getter @Setter
public class TipoTramo extends TipoTramoDTO {

    // atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "nombre", nullable = false, length = 50, unique = true)
    private String nombre;
}
