package utnfc.isi.back.contenedoresservice.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/*
-- Tabla tramo
CREATE TABLE tramo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ruta BIGINT NOT NULL,
    id_camion BIGINT NOT NULL,
    id_tipo_tramo BIGINT NOT NULL,
    id_estado_tramo BIGINT NOT NULL,
    origen BIGINT NOT NULL,
    destino BIGINT NOT NULL,
    fecha_hora_inicio TIMESTAMP,
    fecha_hora_fin TIMESTAMP,
    costo_aproximado DECIMAL(10,2),
    costo_real DECIMAL(10,2),

    -- NUEVAS COLUMNAS REQUERIDAS
    distancia_km DECIMAL(10,2),
    tiempo_estimado_minutos BIGINT,

    CONSTRAINT fk_tramo_ruta
        FOREIGN KEY(id_ruta)
        REFERENCES ruta(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_tramo_camion
        FOREIGN KEY(id_camion)
        REFERENCES camion(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_tramo_tipo_tramo
        FOREIGN KEY(id_tipo_tramo)
        REFERENCES tipo_tramo(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_tramo_estado_tramo
        FOREIGN KEY(id_estado_tramo)
        REFERENCES estado_tramo(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_tramo_origen_direccion
        FOREIGN KEY(origen)
        REFERENCES direccion(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_tramo_destino_direccion
        FOREIGN KEY(destino)
        REFERENCES direccion(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT chk_tramo_origen_destino
        CHECK (origen <> destino)
);
 */

@Entity
@Table(name = "tramo")
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
@AllArgsConstructor
@Getter @Setter
public class Tramo {

    // atributos
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "id_camion", nullable = false)
    private Long idCamion;

    @Column(name = "origen", nullable = false)
    private Long origen;

    @Column(name = "destino", nullable = false)
    private Long destino;

    @Column(name = "fecha_hora_inicio")
    private LocalDateTime fechaHoraInicio;

    @Column(name = "fecha_hora_fin")
    private LocalDateTime fechaHoraFin;

    @Column(name = "costo_aproximado")
    private BigDecimal costoAproximado;

    @Column(name = "costo_real")
    private BigDecimal costoReal;

    @Column(name = "distancia_km")
    private BigDecimal distanciaKm;

    @Column(name = "tiempo_estimado_minutos")
    private Long tiempoEstimadoMinutos;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_ruta", nullable = false)
    private Ruta ruta;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tipo_tramo", nullable = false)
    private TipoTramo tipoTramo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_estado_tramo", nullable = false)
    private EstadoTramo estadoTramo;
}
