-- Tabla pais
CREATE TABLE pais (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      nombre VARCHAR(50) NOT NULL UNIQUE
);

-- Tabla provincia
CREATE TABLE provincia (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nombre VARCHAR(50) NOT NULL,
                           id_pais BIGINT NOT NULL,
                           CONSTRAINT fk_provincia_pais
                               FOREIGN KEY(id_pais)
                                   REFERENCES pais(id)
                                   ON DELETE CASCADE
                                   ON UPDATE CASCADE
);

-- Tabla ciudad
CREATE TABLE ciudad (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nombre VARCHAR(50) NOT NULL,
                        id_provincia BIGINT NOT NULL,
                        CONSTRAINT fk_ciudad_provincia
                            FOREIGN KEY(id_provincia)
                                REFERENCES provincia(id)
                                ON DELETE CASCADE
                                ON UPDATE CASCADE
);

-- Tabla barrio
CREATE TABLE barrio (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nombre VARCHAR(50) NOT NULL,
                        id_ciudad BIGINT NOT NULL,
                        CONSTRAINT fk_barrio_ciudad
                            FOREIGN KEY(id_ciudad)
                                REFERENCES ciudad(id)
                                ON DELETE CASCADE
                                ON UPDATE CASCADE
);

-- Tabla calle
CREATE TABLE calle (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nombre VARCHAR(100) NOT NULL,
                       id_barrio BIGINT NOT NULL,
                       CONSTRAINT fk_calle_barrio
                           FOREIGN KEY(id_barrio)
                               REFERENCES barrio(id)
                               ON DELETE CASCADE
                               ON UPDATE CASCADE
);

-- Tabla cliente
CREATE TABLE cliente (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         documento VARCHAR(30) NOT NULL UNIQUE,
                         nombre VARCHAR(50) NOT NULL,
                         apellido VARCHAR(50) NOT NULL,
                         email VARCHAR(100) NOT NULL UNIQUE,
                         telefono VARCHAR(20) NOT NULL
);

-- Tabla estado_solicitud
CREATE TABLE estado_solicitud (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  nombre VARCHAR(20) NOT NULL UNIQUE
);

-- Tabla estado_contenedor
CREATE TABLE estado_contenedor (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   nombre VARCHAR(20) NOT NULL UNIQUE
);

-- Tabla contenedor
CREATE TABLE contenedor (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            id_estado_contenedor BIGINT NOT NULL,
                            peso DECIMAL(10,2) NOT NULL,
                            volumen DECIMAL(10,2) NOT NULL,
                            id_cliente BIGINT NOT NULL,
                            CONSTRAINT fk_contenedor_cliente
                                FOREIGN KEY(id_cliente)
                                    REFERENCES cliente(id)
                                    ON DELETE CASCADE
                                    ON UPDATE CASCADE,
                            CONSTRAINT fk_contenedor_estado_contenedor
                                FOREIGN KEY(id_estado_contenedor)
                                    REFERENCES estado_contenedor(id)
                                    ON DELETE CASCADE
                                    ON UPDATE CASCADE
);

-- Tabla tipo_camion
CREATE TABLE tipo_camion (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nombre VARCHAR(50) NOT NULL UNIQUE
);

-- Tabla transportista
CREATE TABLE transportista (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               documento VARCHAR(30) NOT NULL UNIQUE,
                               nombre VARCHAR(50) NOT NULL,
                               apellido VARCHAR(50) NOT NULL,
                               email VARCHAR(100) NOT NULL UNIQUE,
                               telefono VARCHAR(20) NOT NULL
);

-- Tabla camion
CREATE TABLE camion (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        id_transportista BIGINT,
                        id_tipo_camion BIGINT,
                        patente VARCHAR(20) NOT NULL UNIQUE,
                        capacidad_peso DECIMAL(10,2) NOT NULL,
                        capacidad_volumen DECIMAL(10,2) NOT NULL,
                        disponible BOOLEAN NOT NULL DEFAULT TRUE,
                        costo_base_km DECIMAL(10,2),
                        consumo_combustible_promedio DECIMAL(5,2),
                        CONSTRAINT fk_camion_transportista
                            FOREIGN KEY(id_transportista)
                                REFERENCES transportista(id)
                                ON DELETE CASCADE
                                ON UPDATE CASCADE,
                        CONSTRAINT fk_camion_tipo_camion
                            FOREIGN KEY(id_tipo_camion)
                                REFERENCES tipo_camion(id)
                                ON DELETE CASCADE
                                ON UPDATE CASCADE
);

-- Tabla solicitud
CREATE TABLE solicitud (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           id_contenedor BIGINT NOT NULL,
                           id_cliente BIGINT NOT NULL,
                           id_estado_solicitud BIGINT NOT NULL,
                           id_camion BIGINT,
                           fecha_creacion DATE,
                           costo_estimado DECIMAL(10,2),
                           tiempo_estimado DECIMAL(10,2),
                           costo_final DECIMAL(10,2),
                           tiempo_real DECIMAL(10,2),
                           CONSTRAINT fk_solicitud_contenedor
                               FOREIGN KEY(id_contenedor)
                                   REFERENCES contenedor(id)
                                   ON UPDATE CASCADE
                                   ON DELETE CASCADE,
                           CONSTRAINT fk_solicitud_cliente
                               FOREIGN KEY(id_cliente)
                                   REFERENCES cliente(id)
                                   ON UPDATE CASCADE
                                   ON DELETE CASCADE,
                           CONSTRAINT fk_solicitud_estado_solicitud
                               FOREIGN KEY(id_estado_solicitud)
                                   REFERENCES estado_solicitud(id)
                                   ON DELETE CASCADE
                                   ON UPDATE CASCADE,
                           CONSTRAINT fk_solicitud_camion
                               FOREIGN KEY(id_camion)
                                   REFERENCES camion(id)
                                   ON UPDATE CASCADE
                                   ON DELETE SET NULL
);

CREATE TABLE solicitud_estado_historial (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            id_solicitud BIGINT NOT NULL,
                                            id_estado_solicitud BIGINT NOT NULL,
                                            fecha_registro TIMESTAMP NOT NULL DEFAULT NOW(),
                                            CONSTRAINT fk_historial_solicitud
                                                FOREIGN KEY (id_solicitud)
                                                    REFERENCES solicitud(id)
                                                    ON DELETE CASCADE
                                                    ON UPDATE CASCADE,
                                            CONSTRAINT fk_historial_estado
                                                FOREIGN KEY (id_estado_solicitud)
                                                    REFERENCES estado_solicitud(id)
                                                    ON DELETE RESTRICT
                                                    ON UPDATE CASCADE
);

-- Tabla direccion
CREATE TABLE direccion (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nro_calle VARCHAR(20) NOT NULL,
                           id_calle BIGINT NOT NULL,
                           id_cliente BIGINT,
                           piso VARCHAR(10),
                           dpto VARCHAR(10),
                           observaciones VARCHAR(100),
                           codigo_postal VARCHAR(20),
                           CONSTRAINT fk_direccion_calle
                               FOREIGN KEY (id_calle)
                                   REFERENCES calle(id)
                                   ON DELETE CASCADE
                                   ON UPDATE CASCADE,
                           CONSTRAINT fk_direccion_cliente
                               FOREIGN KEY (id_cliente)
                                   REFERENCES cliente(id)
                                   ON DELETE CASCADE
                                   ON UPDATE CASCADE
);

-- Tabla geolocalizacion
CREATE TABLE geolocalizacion (
                                 id_direccion BIGINT PRIMARY KEY,
                                 latitud DECIMAL(9,6) NOT NULL,
                                 longitud DECIMAL(9,6) NOT NULL,
                                 CONSTRAINT fk_geolocalizacion_direccion
                                     FOREIGN KEY(id_direccion)
                                         REFERENCES direccion(id)
                                         ON DELETE CASCADE
                                         ON UPDATE CASCADE
);

-- Tabla ruta
CREATE TABLE ruta (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      cantidad_tramos INTEGER NOT NULL,
                      cantidad_depositos INTEGER NOT NULL,
                      distancia_total_km DECIMAL(10,2),
                      tiempo_total_minutos BIGINT,
                      costo_total DECIMAL(10,2),
                      seleccionada BOOLEAN DEFAULT FALSE,
                      id_solicitud BIGINT NOT NULL,
                      CONSTRAINT fk_ruta_solicitud
                          FOREIGN KEY(id_solicitud)
                              REFERENCES solicitud(id)
                              ON DELETE CASCADE
                              ON UPDATE CASCADE
);

-- Tabla tipo_tramo
CREATE TABLE tipo_tramo (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nombre VARCHAR(50) NOT NULL UNIQUE
);

-- Tabla estado_tramo
CREATE TABLE estado_tramo (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nombre VARCHAR(20) NOT NULL UNIQUE
);

-- Tabla tramo
CREATE TABLE tramo (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       id_ruta BIGINT NOT NULL,
                       id_camion BIGINT NOT NULL,
                       id_tipo_tramo BIGINT NOT NULL,
                       id_estado_tramo BIGINT NOT NULL,
                       origen BIGINT NOT NULL,
                       destino BIGINT NOT NULL,
                       fecha_hora_inicio TIMESTAMP,
                       fecha_hora_fin TIMESTAMP,
                       costo_aproximado DECIMAL(10,2),
                       costo_real DECIMAL(10,2),

    -- NUEVAS COLUMNAS REQUERIDAS
                       distancia_km DECIMAL(10,2),
                       tiempo_estimado_minutos BIGINT,

                       CONSTRAINT fk_tramo_ruta
                           FOREIGN KEY(id_ruta)
                               REFERENCES ruta(id)
                               ON DELETE CASCADE
                               ON UPDATE CASCADE,

                       CONSTRAINT fk_tramo_camion
                           FOREIGN KEY(id_camion)
                               REFERENCES camion(id)
                               ON DELETE CASCADE
                               ON UPDATE CASCADE,

                       CONSTRAINT fk_tramo_tipo_tramo
                           FOREIGN KEY(id_tipo_tramo)
                               REFERENCES tipo_tramo(id)
                               ON DELETE CASCADE
                               ON UPDATE CASCADE,

                       CONSTRAINT fk_tramo_estado_tramo
                           FOREIGN KEY(id_estado_tramo)
                               REFERENCES estado_tramo(id)
                               ON DELETE CASCADE
                               ON UPDATE CASCADE,

                       CONSTRAINT fk_tramo_origen_direccion
                           FOREIGN KEY(origen)
                               REFERENCES direccion(id)
                               ON DELETE CASCADE
                               ON UPDATE CASCADE,

                       CONSTRAINT fk_tramo_destino_direccion
                           FOREIGN KEY(destino)
                               REFERENCES direccion(id)
                               ON DELETE CASCADE
                               ON UPDATE CASCADE,

                       CONSTRAINT chk_tramo_origen_destino
                           CHECK (origen <> destino)
);



-- Tabla deposito
CREATE TABLE deposito (
                          id_direccion BIGINT PRIMARY KEY,
                          nombre VARCHAR(50),
                          costo_estadia_diario DECIMAL(10,2) NOT NULL,
                          CONSTRAINT fk_deposito_direccion
                              FOREIGN KEY(id_direccion)
                                  REFERENCES direccion(id)
                                  ON DELETE CASCADE
                                  ON UPDATE CASCADE
);


-- Tabla tarifa
CREATE TABLE tarifa (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        id_tipo_camion BIGINT NOT NULL,
                        rango_peso VARCHAR(20),
                        rango_volumen VARCHAR(20),
                        costo_km DECIMAL(10,2),
                        costo_combustible DECIMAL(10,2),
                        costo_estadia_deposito DECIMAL(10,2),
                        CONSTRAINT fk_tarifa_tipo_camion
                            FOREIGN KEY(id_tipo_camion)
                                REFERENCES tipo_camion(id)
                                ON DELETE RESTRICT
                                ON UPDATE CASCADE,
                        CONSTRAINT uq_tarifa_combinacion
                            UNIQUE (id_tipo_camion, rango_peso, rango_volumen)
);




















